env:
  global:
    - CC_TEST_REPORTER_ID=0
language: node_js
cache:
  directories:
    - ~/.npm
    - "node_modules"
notifications:
  email: false
node_js:
  - '8'
# before_script:
#   - npm prune
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build
# after_script:
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
